# Data-manager

## Export [/import]

### Configure a new templates, devices and flows [POST /import]
Adds a new templates, devices and flows.
+ Request (application/json; charset=utf-8)
  + Headers

            Authorization: Bearer JWT

  + Body

            {
                "devices": [
                    {
                        "id": "14dc1b",
                        "label": "device",
                        "templates": [
                            1
                        ]
                    }
                ],
                "templates": [
                    {
                        "attrs": [
                            {
                                "label": "model-id",
                                "static_value": "model-001",
                                "type": "static",
                                "value_type": "string"
                            },
                            {
                                "label": "temperature",
                                "type": "dynamic",
                                "value_type": "float"
                            }
                        ],
                        "id": 1,
                        "label": "Template"
                    }
                ],
                "flows": [
                    {
                        "name": "Flow",
                        "enabled": true,
                        "id": "a78512b3-33c5-4630-bde4-e73f7ddbe910",
                        "flow": [
                            {
                                "id": "b032cba2.69981",
                                "type": "tab",
                                "name": "Sample flow"
                            },
                            {
                                "id": "f7ae7ff1.f3f3f",
                                "type": "device in",
                                "z": "b032cba2.69981",
                                "name": "device",
                                "device": "{\"id\":\"d4c8f5\"}",
                                "status": "false",
                                "_device_id": "d4c8f5",
                                "_device_label": "",
                                "_device_type": "",
                                "x": 102.5,
                                "y": 164,
                                "wires": [
                                    [
                                        "d4d0b51f.60b0b"
                                    ]
                                ]
                            },
                            {
                                "id": "d4d0b51f.60b0b",
                                "type": "switch",
                                "z": "b032cba2.69981",
                                "name": "",
                                "property": "payload",
                                "propertyType": "msg",
                                "rules": [
                                    {
                                        "t": "eq",
                                        "v": "",
                                        "vt": "str"
                                    }
                                ],
                                "checkall": "true",
                                "outputs": 1,
                                "x": 308,
                                "y": 196,
                                "wires": [
                                    "ad106680.4d93e8"
                                ]
                            },
                            {
                                "id": "ad106680.4d93e8",
                                "type": "change",
                                "z": "b032cba2.69981",
                                "name": "",
                                "rules": [
                                    {
                                        "t": "set",
                                        "p": "payload",
                                        "pt": "msg",
                                        "to": "",
                                        "tot": "str"
                                    }
                                ],
                                "action": "",
                                "property": "",
                                "from": "",
                                "to": "",
                                "reg": false,
                                "x": 434,
                                "y": 263,
                                "wires": []
                            }
                        ],
                        "created": 1542900676927,
                        "updated": 1542900676927
                    }
                ]
            }

+ Response 200 (application/json; charset=utf-8)

+ Response 400

+ Response 500

## Export [/export]

### Get all data to be exported [GET /export]
Returns all currently configured templates, devices and flows
+ Request (application/json; charset=utf-8)
  + Headers

            Authorization: Bearer JWT

+ Response 200 (application/json; charset=utf-8)

+ Response 500
