# Data-manager

## Import [/import]

### Configure a new templates, devices and flows [POST /import]
Returns all currently configured flows
+ Request (application/json; charset=utf-8)
  + Headers

            Authorization: Bearer JWT

  + Body

            {
                "devices": [
                    {
                        "id": "9bbd77",
                        "label": "device",
                        "templates": [
                            296
                        ],
                        "attrs": [
                            {
                                "label": "temp",
                                "static_value": "",
                                "template_id": "296",
                                "type": "dynamic",
                                "value_type": "float"
                            },
                            {
                                "label": "Name",
                                "static_value": "Device",
                                "template_id": "296",
                                "type": "static",
                                "value_type": "string"
                            }
                        ]
                    }
                ],
                "templates": [
                    {
                        "attrs": [
                            {
                                "id": 673,
                                "label": "temp",
                                "metadata": [
                                    {
                                        "created": "2019-01-09T11:25:04.119784+00:00",
                                        "id": 675,
                                        "label": "meta",
                                        "static_value": "meta",
                                        "type": "meta",
                                        "value_type": "string"
                                    }
                                ],
                                "static_value": "",
                                "template_id": "296",
                                "type": "dynamic",
                                "value_type": "float"
                            },
                            {
                                "id": 674,
                                "label": "Name",
                                "static_value": "Name",
                                "template_id": "296",
                                "type": "static",
                                "value_type": "string"
                            }
                        ],
                        "id": 296,
                        "label": "Tempalte"
                    }
                ],
                "flows": [
                    {
                        "name": "flow",
                        "enabled": true,
                        "id": "20c6c697-3d3a-4706-8267-72669a6016de",
                        "flow": [
                            {
                                "id": "8a89221c.f5477",
                                "type": "tab",
                                "label": "Flow 1"
                            },
                            {
                                "id": "1dfbd338.9b187d",
                                "type": "device in",
                                "z": "8a89221c.f5477",
                                "name": "Device",
                                "device_source_id": "device (9bbd77)",
                                "status": "false",
                                "_device_id": "9bbd77",
                                "_device_label": "",
                                "_device_type": "",
                                "x": 147.5,
                                "y": 98,
                                "wires": [
                                    [
                                        "92f3408b.cb051"
                                    ]
                                ]
                            },
                            {
                                "id": "92f3408b.cb051",
                                "type": "http",
                                "z": "8a89221c.f5477",
                                "name": "",
                                "method": "GET",
                                "ret": "txt",
                                "body": "payload",
                                "response": "payload.response",
                                "url": "http://ptsv2.com/t/03n2y-1547033185/post",
                                "x": 254.5,
                                "y": 195,
                                "wires": [
                                    []
                                ]
                            }
                        ],
                        "created": 1547033210480,
                        "updated": 1547033210480
                    }
                ]
            }

+ Response 200 (application/json; charset=utf-8)

  + Body

            {
                "devices": [
                    {
                        "id": "b59044",
                        "label": "device"
                    }
                ],
                "templates": [
                    {
                        "attrs": [
                            {
                                "created": "2018-11-27T11:40:50.755884+00:00",
                                "id": 47,
                                "label": "model-id",
                                "static_value": "model-001",
                                "template_id": "24",
                                "type": "static",
                                "value_type": "string"
                            },
                            {
                                "created": "2018-11-27T11:40:50.813644+00:00",
                                "id": 48,
                                "label": "temperature",
                                "template_id": "24",
                                "type": "dynamic",
                                "value_type": "float"
                            }
                        ],
                        "config_attrs": [],
                        "created": "2018-11-27T11:40:50.754898+00:00",
                        "data_attrs": [
                            {
                                "created": "2018-11-27T11:40:50.755884+00:00",
                                "id": 47,
                                "label": "model-id",
                                "static_value": "model-001",
                                "template_id": "24",
                                "type": "static",
                                "value_type": "string"
                            },
                            {
                                "created": "2018-11-27T11:40:50.813644+00:00",
                                "id": 48,
                                "label": "temperature",
                                "template_id": "24",
                                "type": "dynamic",
                                "value_type": "float"
                            }
                        ],
                        "id": 24,
                        "label": "Template"
                    }
                ],
                "flows": [
                    {
                        "message": "ok",
                        "flow": {
                            "name": "Flow",
                            "enabled": true,
                            "id": "7339c7b7-bd30-4515-991c-e576e76bd184",
                            "flow": [
                                {
                                    "id": "b032cba2.69981",
                                    "type": "tab",
                                    "name": "Sample flow"
                                },
                                {
                                    "id": "f7ae7ff1.f3f3f",
                                    "type": "device in",
                                    "z": "b032cba2.69981",
                                    "name": "device",
                                    "device": "{\"id\":\"d4c8f5\"}",
                                    "status": "false",
                                    "_device_id": "d4c8f5",
                                    "_device_label": "",
                                    "_device_type": "",
                                    "x": 102.5,
                                    "y": 164,
                                    "wires": [
                                        [
                                            "d4d0b51f.60b0b"
                                        ]
                                    ]
                                },
                                {
                                    "id": "d4d0b51f.60b0b",
                                    "type": "switch",
                                    "z": "b032cba2.69981",
                                    "name": "",
                                    "property": "payload",
                                    "propertyType": "msg",
                                    "rules": [
                                        {
                                            "t": "eq",
                                            "v": "",
                                            "vt": "str"
                                        }
                                    ],
                                    "checkall": "true",
                                    "outputs": 1,
                                    "x": 308,
                                    "y": 196,
                                    "wires": [
                                        "ad106680.4d93e8"
                                    ]
                                },
                                {
                                    "id": "ad106680.4d93e8",
                                    "type": "change",
                                    "z": "b032cba2.69981",
                                    "name": "",
                                    "rules": [
                                        {
                                            "t": "set",
                                            "p": "payload",
                                            "pt": "msg",
                                            "to": "",
                                            "tot": "str"
                                        }
                                    ],
                                    "action": "",
                                    "property": "",
                                    "from": "",
                                    "to": "",
                                    "reg": false,
                                    "x": 434,
                                    "y": 263,
                                    "wires": []
                                }
                            ],
                            "created": 1543318850887,
                            "updated": 1543318850887
                        }
                    }
                ]
            }

+ Response 400 (application/json; charset=utf-8)

  + Body

            {
                "message": "message"
            }

## Export [/export]

### Get all data to be exported [GET /export]
Return all currently configured. Templates, devices and flows.
+ Request (application/json; charset=utf-8)
  + Headers

            Authorization: Bearer JWT

+ Response 200 (application/json; charset=utf-8)

  + Body

            {
              "devices": [
                  {
                      "id": "b65f24",
                      "label": "device",
                      "templates": [
                          776
                      ],
                      "attrs": [
                          {
                              "id": 2181,
                              "label": "temp",
                              "metadata": [
                                  {
                                      "created": "2019-01-11T16:49:07.960939+00:00",
                                      "id": 2183,
                                      "label": "meta",
                                      "static_value": "meta",
                                      "type": "meta",
                                      "updated": null,
                                      "value_type": "string"
                                  }
                              ],
                              "static_value": "",
                              "template_id": "776",
                              "type": "dynamic",
                              "value_type": "float"
                          },
                          {
                              "id": 2182,
                              "label": "Name",
                              "static_value": "Device",
                              "template_id": "776",
                              "type": "static",
                              "value_type": "string"
                          }
                      ]
                  }
              ],
              "templates": [
                  {
                      "attrs": [
                          {
                              "id": 2181,
                              "label": "temp",
                              "metadata": [
                                  {
                                      "created": "2019-01-11T16:49:07.960939+00:00",
                                      "id": 2183,
                                      "label": "meta",
                                      "static_value": "meta",
                                      "type": "meta",
                                      "updated": null,
                                      "value_type": "string"
                                  }
                              ],
                              "static_value": "",
                              "template_id": "776",
                              "type": "dynamic",
                              "value_type": "float"
                          },
                          {
                              "id": 2182,
                              "label": "Name",
                              "static_value": "Name",
                              "template_id": "776",
                              "type": "static",
                              "value_type": "string"
                          }
                      ],
                      "id": 776,
                      "label": "Tempalte"
                  }
              ],
              "flows": [
                  {
                      "name": "flow",
                      "enabled": true,
                      "id": "18f97f09-cec9-47ec-936d-f4389173f2c0",
                      "flow": [
                          {
                              "id": "8a89221c.f5477",
                              "type": "tab",
                              "label": "Flow 1"
                          },
                          {
                              "id": "1dfbd338.9b187d",
                              "type": "device in",
                              "z": "8a89221c.f5477",
                              "name": "Device",
                              "device_source_id": "Device (b65f24)",
                              "status": "false",
                              "_device_id": "b65f24",
                              "_device_label": "",
                              "_device_type": "",
                              "x": 147.5,
                              "y": 98,
                              "wires": [
                                  [
                                      "92f3408b.cb051"
                                  ]
                              ]
                          },
                          {
                              "id": "92f3408b.cb051",
                              "type": "http",
                              "z": "8a89221c.f5477",
                              "name": "",
                              "method": "GET",
                              "ret": "txt",
                              "body": "payload",
                              "response": "payload.response",
                              "url": "http://ptsv2.com/t/03n2y-1547033185/post",
                              "x": 254.5,
                              "y": 195,
                              "wires": [
                                  []
                              ]
                          }
                      ],
                      "created": 1547225348029,
                      "updated": 1547225348029
                  }
              ]
          }

+ Response 400 (application/json; charset=utf-8)

  + Body

            {
                "message": "message"
            }
