# Data-manager

## Import [/import]

### Configure a new templates, devices and flows [POST /import]
Returns all currently configured flows
+ Request (application/json; charset=utf-8)
  + Headers

            Authorization: Bearer JWT

  + Body

            {
                "devices": [
                    {
                        "id": "14dc1b",
                        "label": "device",
                        "templates": [
                            1
                        ]
                    }
                ],
                "templates": [
                    {
                        "attrs": [
                            {
                                "label": "model-id",
                                "static_value": "model-001",
                                "type": "static",
                                "value_type": "string"
                            },
                            {
                                "label": "temperature",
                                "type": "dynamic",
                                "value_type": "float"
                            }
                        ],
                        "id": 1,
                        "label": "Template"
                    }
                ],
                "flows": [
                    {
                        "name": "Flow",
                        "enabled": true,
                        "id": "a78512b3-33c5-4630-bde4-e73f7ddbe910",
                        "flow": [
                            {
                                "id": "b032cba2.69981",
                                "type": "tab",
                                "name": "Sample flow"
                            },
                            {
                                "id": "f7ae7ff1.f3f3f",
                                "type": "device in",
                                "z": "b032cba2.69981",
                                "name": "device",
                                "device": "{\"id\":\"d4c8f5\"}",
                                "status": "false",
                                "_device_id": "d4c8f5",
                                "_device_label": "",
                                "_device_type": "",
                                "x": 102.5,
                                "y": 164,
                                "wires": [
                                    [
                                        "d4d0b51f.60b0b"
                                    ]
                                ]
                            },
                            {
                                "id": "d4d0b51f.60b0b",
                                "type": "switch",
                                "z": "b032cba2.69981",
                                "name": "",
                                "property": "payload",
                                "propertyType": "msg",
                                "rules": [
                                    {
                                        "t": "eq",
                                        "v": "",
                                        "vt": "str"
                                    }
                                ],
                                "checkall": "true",
                                "outputs": 1,
                                "x": 308,
                                "y": 196,
                                "wires": [
                                    "ad106680.4d93e8"
                                ]
                            },
                            {
                                "id": "ad106680.4d93e8",
                                "type": "change",
                                "z": "b032cba2.69981",
                                "name": "",
                                "rules": [
                                    {
                                        "t": "set",
                                        "p": "payload",
                                        "pt": "msg",
                                        "to": "",
                                        "tot": "str"
                                    }
                                ],
                                "action": "",
                                "property": "",
                                "from": "",
                                "to": "",
                                "reg": false,
                                "x": 434,
                                "y": 263,
                                "wires": []
                            }
                        ],
                        "created": 1542900676927,
                        "updated": 1542900676927
                    }
                ]
            }

+ Response 200 (application/json; charset=utf-8)

  + Body

            {
                "devices": [
                    {
                        "id": "b59044",
                        "label": "device"
                    }
                ],
                "templates": [
                    {
                        "attrs": [
                            {
                                "created": "2018-11-27T11:40:50.755884+00:00",
                                "id": 47,
                                "label": "model-id",
                                "static_value": "model-001",
                                "template_id": "24",
                                "type": "static",
                                "value_type": "string"
                            },
                            {
                                "created": "2018-11-27T11:40:50.813644+00:00",
                                "id": 48,
                                "label": "temperature",
                                "template_id": "24",
                                "type": "dynamic",
                                "value_type": "float"
                            }
                        ],
                        "config_attrs": [],
                        "created": "2018-11-27T11:40:50.754898+00:00",
                        "data_attrs": [
                            {
                                "created": "2018-11-27T11:40:50.755884+00:00",
                                "id": 47,
                                "label": "model-id",
                                "static_value": "model-001",
                                "template_id": "24",
                                "type": "static",
                                "value_type": "string"
                            },
                            {
                                "created": "2018-11-27T11:40:50.813644+00:00",
                                "id": 48,
                                "label": "temperature",
                                "template_id": "24",
                                "type": "dynamic",
                                "value_type": "float"
                            }
                        ],
                        "id": 24,
                        "label": "Template"
                    }
                ],
                "flows": [
                    {
                        "message": "ok",
                        "flow": {
                            "name": "Flow",
                            "enabled": true,
                            "id": "7339c7b7-bd30-4515-991c-e576e76bd184",
                            "flow": [
                                {
                                    "id": "b032cba2.69981",
                                    "type": "tab",
                                    "name": "Sample flow"
                                },
                                {
                                    "id": "f7ae7ff1.f3f3f",
                                    "type": "device in",
                                    "z": "b032cba2.69981",
                                    "name": "device",
                                    "device": "{\"id\":\"d4c8f5\"}",
                                    "status": "false",
                                    "_device_id": "d4c8f5",
                                    "_device_label": "",
                                    "_device_type": "",
                                    "x": 102.5,
                                    "y": 164,
                                    "wires": [
                                        [
                                            "d4d0b51f.60b0b"
                                        ]
                                    ]
                                },
                                {
                                    "id": "d4d0b51f.60b0b",
                                    "type": "switch",
                                    "z": "b032cba2.69981",
                                    "name": "",
                                    "property": "payload",
                                    "propertyType": "msg",
                                    "rules": [
                                        {
                                            "t": "eq",
                                            "v": "",
                                            "vt": "str"
                                        }
                                    ],
                                    "checkall": "true",
                                    "outputs": 1,
                                    "x": 308,
                                    "y": 196,
                                    "wires": [
                                        "ad106680.4d93e8"
                                    ]
                                },
                                {
                                    "id": "ad106680.4d93e8",
                                    "type": "change",
                                    "z": "b032cba2.69981",
                                    "name": "",
                                    "rules": [
                                        {
                                            "t": "set",
                                            "p": "payload",
                                            "pt": "msg",
                                            "to": "",
                                            "tot": "str"
                                        }
                                    ],
                                    "action": "",
                                    "property": "",
                                    "from": "",
                                    "to": "",
                                    "reg": false,
                                    "x": 434,
                                    "y": 263,
                                    "wires": []
                                }
                            ],
                            "created": 1543318850887,
                            "updated": 1543318850887
                        }
                    }
                ]
            }


## Export [/export]

### Get all data to be exported [GET /export]
Return all currently configured. Templates, devices and flows.
+ Request (application/json; charset=utf-8)
  + Headers

            Authorization: Bearer JWT

+ Response 200 (application/json; charset=utf-8)

  + Body

            {
                "devices": [
                    {
                        "id": "e98b8",
                        "label": "device",
                        "templates": [
                            1
                        ]
                    }
                ],
                "templates": [
                    {
                        "attrs": [
                            {
                                "label": "temp",
                                "static_value": "",
                                "type": "dynamic",
                                "value_type": "float"
                            },
                            {
                                "label": "protocol",
                                "static_value": "mqtt",
                                "type": "meta",
                                "value_type": "string"
                            }
                        ],
                        "id": 1,
                        "label": "template"
                    }
                ],
                "flows": [
                    {
                        "name": "flow",
                        "enabled": true,
                        "id": "c579c542-84a3-41bb-b646-7c01085ee0ae",
                        "flow": [
                            {
                                "id": "ff3fe030.635ae",
                                "type": "tab",
                                "label": "Flow 1"
                            },
                            {
                                "id": "ba0fbd0c.ec663",
                                "type": "device in",
                                "z": "ff3fe030.635ae",
                                "name": "device",
                                "device_source_id": "device (e98b8)",
                                "status": "false",
                                "_device_id": "",
                                "_device_label": "",
                                "_device_type": "",
                                "x": 146.5,
                                "y": 182,
                                "wires": [
                                    [
                                        "659aeae8.bb11e4"
                                    ]
                                ]
                            },
                            {
                                "id": "659aeae8.bb11e4",
                                "type": "switch",
                                "z": "ff3fe030.635ae",
                                "name": "",
                                "property": "payload",
                                "propertyType": "msg",
                                "rules": [
                                    {
                                        "t": "eq",
                                        "v": ""
                                    }
                                ],
                                "checkall": "true",
                                "outputs": 1,
                                "x": 340.5,
                                "y": 237,
                                "wires": [
                                    [
                                        "232ae73c.81be08"
                                    ]
                                ]
                            },
                            {
                                "id": "232ae73c.81be08",
                                "type": "email",
                                "z": "ff3fe030.635ae",
                                "server": "gmail-smtp-in.l.google.com",
                                "port": "25",
                                "secure": false,
                                "name": "",
                                "dname": "",
                                "userid": "",
                                "password": "",
                                "x": 564.5,
                                "y": 324,
                                "wires": []
                            }
                        ],
                        "created": 1543408871066,
                        "updated": 1543408871066
                    }
                ]
            }
