FROM node:8-alpine

WORKDIR /opt/managedata

RUN apk --no-cache add gcc g++ bash musl-dev make python

COPY package.json ./package.json

RUN npm install

RUN apk --no-cache add gcc g++ bash musl-dev make python

COPY . .

EXPOSE 3000

CMD ["npm", "start"]
